# Generated by Django 5.1 on 2026-01-03 22:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_alter_customuser_first_name_alter_customuser_groups_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance_locked', models.DecimalField(decimal_places=2, default=0, help_text='Balance locked in active module deposits', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_available', models.DecimalField(decimal_places=2, default=0, help_text='Balance available for payout', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_paid_out', models.DecimalField(decimal_places=2, default=0, help_text='Total already paid out', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='ModuleDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the learning object')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('settled', 'Settled')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, help_text='Timestamp when settlement completed', null=True)),
                ('content_type', models.ForeignKey(help_text='Type of learning object (e.g., KerdoivKitoltes)', on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module Deposit',
                'verbose_name_plural': 'Module Deposits',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('deposit', 'Deposit'), ('refund', 'Refund'), ('system_fee', 'System Fee'), ('loss', 'Loss'), ('payout', 'Payout')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive, type determines debit/credit', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('idempotency_key', models.CharField(db_index=True, help_text='Format: {deposit_id}:{entry_type}', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('related_deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='monetization.moduledeposit')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='moduledeposit',
            index=models.Index(fields=['user', 'status'], name='monetizatio_user_id_d72953_idx'),
        ),
        migrations.AddIndex(
            model_name='moduledeposit',
            index=models.Index(fields=['content_type', 'object_id'], name='monetizatio_content_1d2174_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['user', 'created_at'], name='monetizatio_user_id_925faa_idx'),
        ),
    ]
