# Generated by Django 5.1 on 2024-09-11 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OsszesitettPontszam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osszes_pont', models.IntegerField(default=0)),
                ('atlag_hatekonysag', models.FloatField(default=0)),
                ('utolso_frissites', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='osszesitett_pontszam', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pontszam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tevekenyseg', models.CharField(max_length=100)),
                ('pontszam', models.IntegerField(default=0)),
                ('max_pontszam', models.IntegerField(default=0)),
                ('datum', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontszamok', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pontszám',
                'verbose_name_plural': 'Pontszámok',
            },
        ),
    ]
