# Generated by Django 5.1 on 2024-10-07 16:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pont', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kihivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tevekenyseg', models.CharField(max_length=100)),
                ('pontszam', models.IntegerField(default=0)),
                ('max_pontszam', models.IntegerField(default=0)),
                ('datum', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kihivasok', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kihívás',
                'verbose_name_plural': 'Kihívások',
            },
        ),
    ]
