# Generated by Django 5.1 on 2025-12-30 21:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pont', '0002_kihivas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True)),
                ('nev', models.CharField(max_length=100)),
                ('leiras', models.TextField()),
                ('ikon', models.CharField(help_text='Font Awesome ikon vagy emoji', max_length=50)),
                ('tipus', models.CharField(choices=[('teljesitmeny', 'Teljesítmény'), ('sorozat', 'Sorozat'), ('specialis', 'Speciális'), ('kihivas', 'Kihívás')], default='teljesitmeny', max_length=20)),
                ('feltetel', models.JSONField(default=dict, help_text='Megszerzési feltételek JSON formátumban')),
                ('pont_ertek', models.IntegerField(default=0, help_text='XP jutalom a badge megszerzéséért')),
                ('ritka', models.BooleanField(default=False, help_text='Ritka badge')),
            ],
            options={
                'verbose_name': 'Kitűző',
                'verbose_name_plural': 'Kitűzők',
            },
        ),
        migrations.CreateModel(
            name='PontozasiKategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(help_text="Egyedi kód (pl. 'szorzas_gyakorlas')", max_length=50, unique=True)),
                ('nev', models.CharField(help_text='Megjelenítendő név', max_length=100)),
                ('leiras', models.TextField(blank=True)),
                ('alap_pont', models.IntegerField(default=10, help_text='Alapértelmezett pontszám')),
                ('max_pont', models.IntegerField(default=20, help_text='Maximum pontszám')),
                ('ikon', models.CharField(blank=True, help_text='Font Awesome ikon kód', max_length=50)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pontozási kategória',
                'verbose_name_plural': 'Pontozási kategóriák',
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktualis_sorozat', models.IntegerField(default=0, help_text='Jelenlegi sorozat hossza (napokban)')),
                ('leghosszabb_sorozat', models.IntegerField(default=0, help_text='Leghosszabb sorozat')),
                ('utolso_aktivitas', models.DateField(blank=True, null=True)),
                ('osszes_aktiv_nap', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sorozat',
                'verbose_name_plural': 'Sorozatok',
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szint', models.IntegerField(default=1, help_text='Jelenlegi szint')),
                ('xp', models.IntegerField(default=0, help_text='Tapasztalati pont')),
                ('kovetkezo_szint_xp', models.IntegerField(default=100, help_text='Következő szinthez szükséges XP')),
                ('rang', models.CharField(default='Kezdő', help_text='Rang neve', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='szint', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Felhasználói szint',
                'verbose_name_plural': 'Felhasználói szintek',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('megszerzve', models.DateTimeField(default=django.utils.timezone.now)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pont.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Felhasználói kitűző',
                'verbose_name_plural': 'Felhasználói kitűzők',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
