"""
Django settings for tanoda project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sb064)&7g&!%wl*s+v(n6g%k%85+6v7&jlbqysj$80owe*hw1x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tanoda',
    'account',
    'navbar',
    'egesz_szamok',
    'pont',
    'plotly_chart',
    'blockly',
    'TRON_Bit',
    'statisztika',
    'mathsolver',  # Add this line
    'kerdoiv',  # Add the new kerdoiv app here
    'threejs_app',  # Three.js alkalmazás
    'monetization',  # Added for Monetization Engine
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tanoda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'tanoda' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tanoda.context_processors.evfolyam_config',
            ],
        },
    },
]

AUTH_USER_MODEL = 'account.CustomUser'

# Login/Logout URLs
LOGIN_REDIRECT_URL = '/'  # Bejelentkezés után a főoldalra irányít
LOGIN_URL = '/accounts/login/'  # Bejelentkezési oldal
LOGOUT_REDIRECT_URL = '/accounts/login/'  # Kijelentkezés után a login oldalra

WSGI_APPLICATION = 'tanoda.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_DIR = os.path.join(BASE_DIR, 'static')

# Definiáljuk az új static mappákat
JS_DIR = os.path.join(STATIC_DIR, 'js')
BLOCKLY_DIR = os.path.join(JS_DIR, 'blockly')
BLOCKLY_TASKS_DIR = os.path.join(BLOCKLY_DIR, 'tasks')
THREE_DIR = os.path.join(JS_DIR, 'three')
CSS_DIR = os.path.join(STATIC_DIR, 'css')
LIBS_DIR = os.path.join(STATIC_DIR, 'libs')

# Fix: Remove the duplicate STATICFILES_DIRS definition
STATICFILES_DIRS = [
    STATIC_DIR,
    JS_DIR,
    BLOCKLY_DIR,
    BLOCKLY_TASKS_DIR,
    THREE_DIR,
    CSS_DIR,
    LIBS_DIR,
]

# Opcionális: Ha használni szeretnéd a collectstatic parancsot production környezetben
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Or BASE_DIR / 'media'


SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True