# Generated by Django 5.1 on 2024-10-11 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelyesValasz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szorzo', models.IntegerField()),
                ('szorzando', models.IntegerField()),
                ('eredmeny', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MegoldasiModszer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leiras', models.CharField(max_length=255)),
                ('alkalmazas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SzorzasiSzabaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leiras', models.CharField(max_length=255)),
                ('magyarazat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HibasValasz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szorzo', models.IntegerField()),
                ('szorzando', models.IntegerField()),
                ('hibas_eredmeny', models.IntegerField()),
                ('helyes_eredmeny', models.IntegerField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('javitva', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hibás válasz',
                'verbose_name_plural': 'Hibás válaszok',
            },
        ),
        migrations.CreateModel(
            name='SzorzasGyakorlatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utolso_frissites', models.DateTimeField(auto_now=True)),
                ('helyes_valaszok', models.ManyToManyField(to='egesz_szamok.helyesvalasz')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='helyesvalasz',
            name='alkalmazott_szabaly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='egesz_szamok.szorzasiszabaly'),
        ),
        migrations.AlterUniqueTogether(
            name='helyesvalasz',
            unique_together={('szorzo', 'szorzando')},
        ),
    ]
