# Generated by Django 5.1 on 2024-10-11 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egesz_szamok', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='helyesvalasz',
            name='nehezsegi_szint',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hibasvalasz',
            name='javitasok_szama',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hibasvalasz',
            name='nehezsegi_szint',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='megoldasimodszer',
            name='nehezsegi_szint',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='szorzasgyakorlatsession',
            name='aktualis_nehezsegi_szint',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='szorzasgyakorlatsession',
            name='gyenge_pontok',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='szorzasiszabaly',
            name='nehezsegi_szint',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='HibaStatisztika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szorzo', models.IntegerField()),
                ('szorzando', models.IntegerField()),
                ('hibak_szama', models.IntegerField(default=0)),
                ('utolso_hiba_datum', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'szorzo', 'szorzando')},
            },
        ),
        migrations.CreateModel(
            name='SzintStatisztika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nehezsegi_szint', models.IntegerField()),
                ('helyes_valaszok_szama', models.IntegerField(default=0)),
                ('osszes_valasz_szama', models.IntegerField(default=0)),
                ('teljesitesi_arany', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'nehezsegi_szint')},
            },
        ),
    ]
