# Generated by Django 5.1 on 2024-10-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egesz_szamok', '0002_helyesvalasz_nehezsegi_szint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='szorzasgyakorlatsession',
            name='megoldott_feladatok',
            field=models.JSONField(default=list),
        ),
    ]
