# Generated by Django 5.1 on 2026-01-18 11:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egesz_szamok', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_module', models.CharField(choices=[('multiplication', 'Szorzás'), ('division', 'Osztás'), ('fractions', 'Törtek')], default='multiplication', max_length=32)),
                ('mode', models.CharField(choices=[('practice', 'Gyakorlás'), ('score', 'Pontozás'), ('challenge', 'Kihívás')], default='practice', max_length=16)),
                ('current_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('current_task_data', models.JSONField(blank=True, default=dict, help_text='Current task: {operand1, operand2, operation, ...}')),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions_vnext', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Session (vNext)',
                'verbose_name_plural': 'Learning Sessions (vNext)',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SESSION_STARTED', 'Session Started'), ('TASK_NEXT_REQUESTED', 'Next Task Requested'), ('ANSWER_SUBMITTED', 'Answer Submitted'), ('LEVEL_RESET_REQUESTED', 'Level Reset Requested'), ('FULL_RESET_REQUESTED', 'Full Reset Requested'), ('MODE_CHANGED', 'Mode Changed'), ('SESSION_ENDED', 'Session Ended'), ('MODULE_CHANGED', 'Module Changed'), ('LEVEL_COMPLETED', 'Level Completed'), ('STREAK_MILESTONE', 'Streak Milestone'), ('CHALLENGE_STARTED', 'Challenge Started'), ('CHALLENGE_ENDED', 'Challenge Ended')], db_index=True, max_length=32)),
                ('client_event_id', models.CharField(db_index=True, help_text='Client-provided idempotency key', max_length=64, unique=True)),
                ('payload', models.JSONField(default=dict, help_text='Event-specific data')),
                ('module', models.CharField(choices=[('multiplication', 'Szorzás'), ('division', 'Osztás'), ('fractions', 'Törtek')], max_length=32)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('epoch', models.IntegerField(default=1, help_text='Reset epoch for this level')),
                ('mode', models.CharField(choices=[('practice', 'Gyakorlás'), ('score', 'Pontozás'), ('challenge', 'Kihívás')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events_vnext', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='egesz_szamok.learningsession')),
            ],
            options={
                'verbose_name': 'Learning Event',
                'verbose_name_plural': 'Learning Events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('multiplication', 'Szorzás'), ('division', 'Osztás'), ('fractions', 'Törtek')], max_length=32)),
                ('level', models.IntegerField()),
                ('epoch', models.IntegerField(default=1)),
                ('operand1', models.IntegerField()),
                ('operand2', models.IntegerField()),
                ('correct_answer', models.IntegerField()),
                ('user_answer', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Time taken to answer in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts_vnext', to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(help_text='The ANSWER_SUBMITTED event that created this attempt', on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='egesz_szamok.learningevent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='egesz_szamok.learningsession')),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attempts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasteryState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('multiplication', 'Szorzás'), ('division', 'Osztás'), ('fractions', 'Törtek')], max_length=32)),
                ('stars', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('completed_levels', models.JSONField(default=list, help_text='List of completed level numbers')),
                ('total_attempts', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('overall_accuracy', models.FloatField(default=0.0)),
                ('total_practice_time_seconds', models.IntegerField(default=0)),
                ('badges', models.JSONField(default=list, help_text='List of earned badge IDs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_states_vnext', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mastery State',
                'verbose_name_plural': 'Mastery States',
            },
        ),
        migrations.CreateModel(
            name='UserLevelProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('multiplication', 'Szorzás'), ('division', 'Osztás'), ('fractions', 'Törtek')], max_length=32)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('epoch', models.IntegerField(default=1, help_text='Current epoch (incremented on reset)')),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress_vnext', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Level Progress',
                'verbose_name_plural': 'User Level Progress',
            },
        ),
        migrations.CreateModel(
            name='GridCellState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('multiplication', 'Szorzás'), ('division', 'Osztás'), ('fractions', 'Törtek')], max_length=32)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('epoch', models.IntegerField(default=1)),
                ('row', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('col', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('state', models.CharField(choices=[('unseen', 'Nem látott'), ('incorrect_recent', 'Nemrég hibás'), ('correct_once', 'Egyszer helyes'), ('correct_stable', 'Stabilan helyes'), ('mastered', 'Elsajátított')], default='unseen', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_correct', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_cells_vnext', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grid Cell State',
                'verbose_name_plural': 'Grid Cell States',
                'indexes': [models.Index(fields=['user', 'module', 'epoch'], name='egesz_szamo_user_id_401642_idx'), models.Index(fields=['user', 'state'], name='egesz_szamo_user_id_c94958_idx')],
                'unique_together': {('user', 'module', 'level', 'epoch', 'row', 'col')},
            },
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['user', 'is_active'], name='egesz_szamo_user_id_050690_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsession',
            index=models.Index(fields=['user', 'active_module'], name='egesz_szamo_user_id_fc6cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['user', 'created_at'], name='egesz_szamo_user_id_1090e1_idx'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['session', 'event_type'], name='egesz_szamo_session_5b8ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='learningevent',
            index=models.Index(fields=['user', 'module', 'level', 'epoch'], name='egesz_szamo_user_id_201477_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'module', 'level', 'epoch'], name='egesz_szamo_user_id_3630b2_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'is_correct', 'created_at'], name='egesz_szamo_user_id_062cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['operand1', 'operand2'], name='egesz_szamo_operand_001bf0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='masterystate',
            unique_together={('user', 'module')},
        ),
        migrations.AddIndex(
            model_name='userlevelprogress',
            index=models.Index(fields=['user', 'module', 'level'], name='egesz_szamo_user_id_36396e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlevelprogress',
            unique_together={('user', 'module', 'level', 'epoch')},
        ),
    ]
