# Generated by Django 5.1 on 2026-01-05 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('status', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='tanoda.notificationevent')),
            ],
        ),
    ]
