# Generated by Django 5.1 on 2025-04-18 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kerdoiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cim', models.CharField(max_length=255, verbose_name='Kérdőív címe')),
                ('leiras', models.TextField(blank=True, null=True, verbose_name='Leírás')),
                ('letrehozas_datum', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozás dátuma')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktív')),
            ],
            options={
                'verbose_name': 'Kérdőív',
                'verbose_name_plural': 'Kérdőívek',
            },
        ),
        migrations.CreateModel(
            name='Kerdes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szoveg', models.TextField(verbose_name='Kérdés szövege')),
                ('tipus', models.CharField(choices=[('FELELETVALASZTOS_EGY', 'Feleletválasztós (egy helyes válasz)'), ('FELELETVALASZTOS_TOBB', 'Feleletválasztós (több helyes válasz)'), ('SZÖVEGES', 'Szöveges válasz')], max_length=50, verbose_name='Kérdés típusa')),
                ('pontszam', models.PositiveIntegerField(default=1, verbose_name='Pontszám')),
                ('sorrend', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
                ('kerdoiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kerdesek', to='kerdoiv.kerdoiv', verbose_name='Kérdőív')),
            ],
            options={
                'verbose_name': 'Kérdés',
                'verbose_name_plural': 'Kérdések',
                'ordering': ['kerdoiv', 'sorrend', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KerdoivKitoltes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitoltes_datum', models.DateTimeField(auto_now_add=True, verbose_name='Kitöltés dátuma')),
                ('pontszam', models.IntegerField(default=0, verbose_name='Elért pontszám')),
                ('befejezve', models.BooleanField(default=False, verbose_name='Befejezve')),
                ('felhasznalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kitöltő')),
                ('kerdoiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kerdoiv.kerdoiv', verbose_name='Kérdőív')),
            ],
            options={
                'verbose_name': 'Kérdőív kitöltés',
                'verbose_name_plural': 'Kérdőív kitöltések',
                'unique_together': {('felhasznalo', 'kerdoiv')},
            },
        ),
        migrations.CreateModel(
            name='Valaszlehetoseg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szoveg', models.CharField(max_length=500, verbose_name='Válasz szövege')),
                ('helyes', models.BooleanField(default=False, verbose_name='Helyes válasz')),
                ('kerdes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valaszlehetosegek', to='kerdoiv.kerdes', verbose_name='Kérdés')),
            ],
            options={
                'verbose_name': 'Válaszlehetőség',
                'verbose_name_plural': 'Válaszlehetőségek',
            },
        ),
        migrations.CreateModel(
            name='TanuloValasz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szoveges_valasz', models.TextField(blank=True, null=True, verbose_name='Szöveges válasz')),
                ('helyes_e', models.BooleanField(blank=True, null=True, verbose_name='Helyes volt-e a válasz?')),
                ('kerdes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kerdoiv.kerdes', verbose_name='Kérdés')),
                ('kitoltes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valaszok', to='kerdoiv.kerdoivkitoltes', verbose_name='Kitöltés')),
                ('valasztott_lehetosegek', models.ManyToManyField(blank=True, to='kerdoiv.valaszlehetoseg', verbose_name='Választott lehetőség(ek)')),
            ],
            options={
                'verbose_name': 'Tanuló válasz',
                'verbose_name_plural': 'Tanuló válaszok',
                'unique_together': {('kitoltes', 'kerdes')},
            },
        ),
    ]
